/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bankmenagement;

/**
 *
 * @author Mishkat Chowdhury
 */
public class SIGNUP extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public SIGNUP() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        NewAccount = new javax.swing.JLabel();
        Name = new javax.swing.JTextField();
        Sname = new javax.swing.JTextField();
        MobileAndEmail = new javax.swing.JTextField();
        newPassword = new javax.swing.JTextField();
        Age = new javax.swing.JLabel();
        Date = new javax.swing.JTextField();
        Male = new javax.swing.JRadioButton();
        Female = new javax.swing.JRadioButton();
        Singup = new javax.swing.JButton();
        Fname = new javax.swing.JLabel();
        Surname = new javax.swing.JLabel();
        emailAndPhone = new javax.swing.JLabel();
        Npassword = new javax.swing.JLabel();
        Other = new javax.swing.JRadioButton();
        LAB = new javax.swing.JLabel();
        lab = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        occup = new javax.swing.JLabel();
        occupation = new javax.swing.JComboBox<>();
        income = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        amount = new javax.swing.JLabel();
        opning = new javax.swing.JComboBox<>();
        CANCLE = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(java.awt.Color.lightGray);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NewAccount.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        NewAccount.setText("Open new Account");
        jPanel1.add(NewAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameActionPerformed(evt);
            }
        });
        jPanel1.add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, 320, 33));

        Sname.setForeground(new java.awt.Color(204, 0, 51));
        Sname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SnameActionPerformed(evt);
            }
        });
        jPanel1.add(Sname, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, 230, 110));

        MobileAndEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MobileAndEmailActionPerformed(evt);
            }
        });
        jPanel1.add(MobileAndEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, 340, 35));

        newPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newPasswordActionPerformed(evt);
            }
        });
        jPanel1.add(newPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, 182, 31));

        Age.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Age.setText("Age:");
        jPanel1.add(Age, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 430, 70, 40));
        jPanel1.add(Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 430, 116, 30));

        buttonGroup1.add(Male);
        Male.setText("Male");
        Male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaleActionPerformed(evt);
            }
        });
        jPanel1.add(Male, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 490, 121, -1));

        buttonGroup1.add(Female);
        Female.setText("Female");
        jPanel1.add(Female, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 490, 89, -1));

        Singup.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Singup.setText("Create");
        Singup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SingupActionPerformed(evt);
            }
        });
        jPanel1.add(Singup, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 730, 139, -1));

        Fname.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Fname.setText("Name:");
        jPanel1.add(Fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 110, -1));

        Surname.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Surname.setText("Address:");
        jPanel1.add(Surname, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 115, -1));

        emailAndPhone.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        emailAndPhone.setText("Email:");
        jPanel1.add(emailAndPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 288, -1));

        Npassword.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Npassword.setText("Password:");
        jPanel1.add(Npassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, -1, -1));

        buttonGroup1.add(Other);
        Other.setText("Other");
        jPanel1.add(Other, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 490, 80, -1));

        LAB.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LAB.setForeground(new java.awt.Color(255, 0, 51));
        jPanel1.add(LAB, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 140, 210, 30));

        lab.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lab.setForeground(new java.awt.Color(255, 51, 0));
        jPanel1.add(lab, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 190, 190, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Gender:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 490, -1, -1));

        occup.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        occup.setForeground(new java.awt.Color(240, 240, 240));
        occup.setText("occupation:");
        jPanel1.add(occup, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 550, -1, -1));

        occupation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "service", "Businessman" }));
        jPanel1.add(occupation, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 550, -1, -1));

        income.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        income.setForeground(new java.awt.Color(240, 240, 240));
        income.setText("Annual Income:");
        jPanel1.add(income, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 600, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10000", "100000", "20000", "200000" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 600, -1, -1));

        amount.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        amount.setForeground(new java.awt.Color(240, 240, 240));
        amount.setText("Opning Amount:");
        jPanel1.add(amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 640, -1, -1));

        opning.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1000", "2000", "3000", "4000" }));
        jPanel1.add(opning, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 640, -1, -1));

        CANCLE.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        CANCLE.setText("Cancel");
        CANCLE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CANCLEActionPerformed(evt);
            }
        });
        jPanel1.add(CANCLE, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 730, 130, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bankmenagement/Bank10.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1040, 810));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 828, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MaleActionPerformed

    private void SingupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SingupActionPerformed
        if(Name.getText().trim().isEmpty()){
            LAB.setText("please enter your first Email");
        }
        if(Sname.getText().trim().isEmpty()){
            lab.setText("please enter your Name");
        }
        else{
            SIGNIN obj = new SIGNIN();
            obj.setVisible(true);
        }
    }//GEN-LAST:event_SingupActionPerformed

    private void NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameActionPerformed

    private void SnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SnameActionPerformed

    }//GEN-LAST:event_SnameActionPerformed

    private void MobileAndEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MobileAndEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MobileAndEmailActionPerformed

    private void CANCLEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CANCLEActionPerformed
     Introduction obj = new Introduction();
     obj.setVisible(true);
    }//GEN-LAST:event_CANCLEActionPerformed

    private void newPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newPasswordActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SIGNUP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SIGNUP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SIGNUP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SIGNUP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SIGNUP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Age;
    private javax.swing.JButton CANCLE;
    private javax.swing.JTextField Date;
    private javax.swing.JRadioButton Female;
    private javax.swing.JLabel Fname;
    private javax.swing.JLabel LAB;
    private javax.swing.JRadioButton Male;
    private javax.swing.JTextField MobileAndEmail;
    private javax.swing.JTextField Name;
    private javax.swing.JLabel NewAccount;
    private javax.swing.JLabel Npassword;
    private javax.swing.JRadioButton Other;
    private javax.swing.JButton Singup;
    private javax.swing.JTextField Sname;
    private javax.swing.JLabel Surname;
    private javax.swing.JLabel amount;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JLabel emailAndPhone;
    private javax.swing.JLabel income;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lab;
    private javax.swing.JTextField newPassword;
    private javax.swing.JLabel occup;
    private javax.swing.JComboBox<String> occupation;
    private javax.swing.JComboBox<String> opning;
    // End of variables declaration//GEN-END:variables
}
